import { describe, expect, it } from "vitest";

import { type GitCommandRunner } from "../../src/git.js";
import { type LlmGenerateRequest, type LlmGenerateResponse, type LlmProvider } from "../../src/llm/provider.js";
import { MockLlmProvider } from "../../src/llm/mockProvider.js";
import { generateCommitMessage } from "../../src/pipeline/generate.js";
import { runCommitMessagePipeline } from "../../src/pipeline/run.js";
import { LOCKFILE_DIFF, SIMPLE_APP_DIFF } from "../fixtures.js";

class Runner implements GitCommandRunner {
  private readonly outputs: Record<string, { stdout: string; stderr?: string; status?: number }>;

  constructor(outputs: Record<string, { stdout: string; stderr?: string; status?: number }>) {
    this.outputs = outputs;
  }

  run(args: string[]) {
    const key = args.join(" ");
    const result = this.outputs[key];
    return {
      stdout: result?.stdout ?? "",
      stderr: result?.stderr ?? "",
      status: result?.status ?? 0,
    };
  }
}

class CountingProvider implements LlmProvider {
  summarizeCalls = 0;

  async generate(request: LlmGenerateRequest): Promise<LlmGenerateResponse> {
    if (request.task === "summarize_chunk") {
      return { text: await this.summarizeChunk() };
    }
    return { text: await this.synthesizeCommit() };
  }

  async summarizeChunk(): Promise<string> {
    this.summarizeCalls += 1;
    return JSON.stringify({
      whatChanged: "Implement large-scale module updates",
      whyLikely: "Core source code behavior changed",
      probableType: "feat",
      importance: 8,
      isNoise: false,
    });
  }

  async synthesizeCommit(): Promise<string> {
    return "feat: implement large-scale module updates";
  }
}

class WeakSummaryProvider implements LlmProvider {
  synthesizeCalls = 0;

  async generate(request: LlmGenerateRequest): Promise<LlmGenerateResponse> {
    if (request.task === "summarize_chunk") {
      return { text: await this.summarizeChunk(request.prompt) };
    }
    return { text: await this.synthesizeCommit() };
  }

  async summarizeChunk(prompt: string): Promise<string> {
    const filePath = prompt.match(/FILE_PATH:\s*(.+)/)?.[1]?.trim() ?? "src/unknown.ts";
    const isCritical = /(^|\/)critical\.ts$/.test(filePath);

    return JSON.stringify({
      whatChanged: `Updated ${filePath}`,
      whyLikely: "Code changes detected",
      probableType: isCritical ? "fix" : "feat",
      importance: isCritical ? 9 : 4,
      isNoise: false,
    });
  }

  async synthesizeCommit(): Promise<string> {
    this.synthesizeCalls += 1;
    return "feat: generated by synthesis";
  }
}

function buildLargeDiff(lineCount: number): string {
  const additions = Array.from(
    { length: lineCount },
    (_, index) => `+export const value_${index} = ${index};`,
  ).join("\n");

  return `diff --git a/src/large.ts b/src/large.ts
index 1234567..89abcde 100644
--- a/src/large.ts
+++ b/src/large.ts
@@ -0,0 +1,${lineCount}
${additions}
`;
}

function buildManyFileDiff(fileCount: number): string {
  const files: string[] = [];
  for (let index = 0; index < fileCount; index += 1) {
    files.push(`diff --git a/src/file-${index}.ts b/src/file-${index}.ts
index 1111111..2222222 100644
--- a/src/file-${index}.ts
+++ b/src/file-${index}.ts
@@ -1 +1 @@
-export const value = ${index};
+export const value = ${index + 1};
`);
  }
  return files.join("\n");
}

const MULTI_FILE_DIFF = `diff --git a/src/noncritical.ts b/src/noncritical.ts
index 1111111..2222222 100644
--- a/src/noncritical.ts
+++ b/src/noncritical.ts
@@ -1 +1 @@
-export const value = 1;
+export const value = 2;
diff --git a/src/critical.ts b/src/critical.ts
index 3333333..4444444 100644
--- a/src/critical.ts
+++ b/src/critical.ts
@@ -1 +1 @@
-export function validate() { return false; }
+export function validate() { return true; }
`;

describe("runCommitMessagePipeline integration", () => {
  it("collects staged diff and generates a conventional commit", async () => {
    const runner = new Runner({
      "diff --cached --no-ext-diff": { stdout: SIMPLE_APP_DIFF },
      "diff --no-ext-diff": { stdout: "" },
    });

    const result = await runCommitMessagePipeline({
      gitRunner: runner,
      provider: new MockLlmProvider(),
    });

    expect(result.hasChanges).toBe(true);
    expect(result.diffSource).toBe("staged");
    expect(result.commitMessage).toMatch(/^(feat|fix|refactor|docs|test|chore):\s+/);
  });

  it("falls back to unstaged diff when staged diff is empty", async () => {
    const runner = new Runner({
      "diff --cached --no-ext-diff": { stdout: "" },
      "diff --no-ext-diff": { stdout: SIMPLE_APP_DIFF },
    });

    const result = await runCommitMessagePipeline({
      gitRunner: runner,
      provider: new MockLlmProvider(),
    });

    expect(result.hasChanges).toBe(true);
    expect(result.diffSource).toBe("unstaged");
  });

  it("splits large diffs into multiple chunk summaries", async () => {
    const provider = new CountingProvider();
    const runner = new Runner({
      "diff --cached --no-ext-diff": { stdout: buildLargeDiff(700) },
    });

    const result = await runCommitMessagePipeline({ gitRunner: runner, provider });

    expect(result.commitMessage).toBe("feat: implement large-scale module updates");
    expect(provider.summarizeCalls).toBeGreaterThan(1);
  });

  it("caps summarize-chunk model calls for very large multi-file diffs", async () => {
    const provider = new CountingProvider();
    const runner = new Runner({
      "diff --cached --no-ext-diff": { stdout: buildManyFileDiff(60) },
    });

    const result = await runCommitMessagePipeline({ gitRunner: runner, provider });

    expect(result.hasChanges).toBe(true);
    expect(result.commitMessage).toBe("feat: implement large-scale module updates");
    expect(provider.summarizeCalls).toBeLessThanOrEqual(24);
  });

  it("uses safe chore fallback when all changes are noise", async () => {
    const runner = new Runner({
      "diff --cached --no-ext-diff": { stdout: LOCKFILE_DIFF },
    });

    const result = await runCommitMessagePipeline({
      gitRunner: runner,
      provider: new MockLlmProvider(),
    });

    expect(result.commitMessage).toBe("chore: update lockfile and generated files");
  });

  it("skips summarize-chunk model calls when all chunks are classified as noise", async () => {
    const provider = new CountingProvider();
    const runner = new Runner({
      "diff --cached --no-ext-diff": { stdout: LOCKFILE_DIFF },
    });

    const result = await runCommitMessagePipeline({
      gitRunner: runner,
      provider,
    });

    expect(result.commitMessage).toBe("chore: update lockfile and generated files");
    expect(provider.summarizeCalls).toBe(0);
  });

  it("falls back to the highest-importance non-noise summary when summaries are weak", async () => {
    const provider = new WeakSummaryProvider();

    const result = await generateCommitMessage({ rawDiff: MULTI_FILE_DIFF }, provider);

    expect(result.commitMessage).toBe("fix: src/critical.ts");
    expect(provider.synthesizeCalls).toBe(0);
  });

  it("throws a clear error when non-empty diff parsing fails", async () => {
    await expect(generateCommitMessage({ rawDiff: "this is not a unified diff" }, new MockLlmProvider())).rejects.toThrow(
      "Unable to parse git diff into file patches",
    );
  });
});
