import { describe, expect, it } from "vitest";

import { detectNoise } from "../../src/diff/noise.js";

describe("detectNoise", () => {
  it("flags lockfiles", () => {
    expect(detectNoise("pnpm-lock.yaml", false).reason).toBe("lockfile");
    expect(detectNoise("apps/web/yarn.lock", false).reason).toBe("lockfile");
  });

  it("flags generated/build outputs and coverage", () => {
    expect(detectNoise("dist/index.js", false).reason).toBe("build_artifact");
    expect(detectNoise("src/__generated__/schema.ts", false).reason).toBe("generated");
    expect(detectNoise("coverage/lcov.info", false).reason).toBe("coverage");
  });

  it("flags sourcemaps and minified files", () => {
    expect(detectNoise("assets/app.js.map", false).reason).toBe("sourcemap");
    expect(detectNoise("assets/app.min.js", false).reason).toBe("minified");
  });

  it("flags binary changes", () => {
    expect(detectNoise("assets/logo.png", true).reason).toBe("binary");
  });

  it("flags generated markers in patch text", () => {
    const patch = `diff --git a/src/api.ts b/src/api.ts
--- a/src/api.ts
+++ b/src/api.ts
@@ -1 +1 @@
-// old
+// @generated by openapi
`;
    expect(detectNoise("src/api.ts", false, patch).reason).toBe("generated");
  });

  it("flags minified-like long-line patches", () => {
    const minifiedPatch = `diff --git a/public/app.js b/public/app.js
--- a/public/app.js
+++ b/public/app.js
@@ -1 +1,3 @@
+(()=>{const a=1,b=2,c=3,d=4,e=5,f=6,g=7,h=8,i=9,j=10,k=11,l=12,m=13,n=14,o=15,p=16,q=17,r=18,s=19,t=20,u=21,v=22,w=23,x=24,y=25,z=26;console.log(a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z)})();
+(()=>{const a=1,b=2,c=3,d=4,e=5,f=6,g=7,h=8,i=9,j=10,k=11,l=12,m=13,n=14,o=15,p=16,q=17,r=18,s=19,t=20,u=21,v=22,w=23,x=24,y=25,z=26;console.log(a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z)})();
+(()=>{const a=1,b=2,c=3,d=4,e=5,f=6,g=7,h=8,i=9,j=10,k=11,l=12,m=13,n=14,o=15,p=16,q=17,r=18,s=19,t=20,u=21,v=22,w=23,x=24,y=25,z=26;console.log(a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z)})();
`;
    expect(detectNoise("public/app.js", false, minifiedPatch).reason).toBe("minified");
  });

  it("keeps normal source files as non-noise", () => {
    const noise = detectNoise("src/services/auth.ts", false);
    expect(noise.isNoise).toBe(false);
    expect(noise.reason).toBe("unknown");
  });
});
