import { describe, expect, it } from "vitest";

import { splitByFile, splitDiffForSummarization } from "../../src/diff/splitByFile.js";

describe("splitByFile", () => {
  it("splits a raw diff into file-level chunks", () => {
    const rawDiff = [
      "diff --git a/src/a.ts b/src/a.ts",
      "index 1111111..2222222 100644",
      "--- a/src/a.ts",
      "+++ b/src/a.ts",
      "@@ -1,1 +1,1 @@",
      "-const a = 1;",
      "+const a = 2;",
      "diff --git a/src/b.ts b/src/b.ts",
      "index 3333333..4444444 100644",
      "--- a/src/b.ts",
      "+++ b/src/b.ts",
      "@@ -1,1 +1,1 @@",
      "-const b = 1;",
      "+const b = 2;",
    ].join("\n");

    const chunks = splitByFile(rawDiff);

    expect(chunks).toHaveLength(2);
    expect(chunks[0].filePath).toBe("src/a.ts");
    expect(chunks[1].filePath).toBe("src/b.ts");
    expect(chunks[0].source).toBe("file");
    expect(chunks[1].source).toBe("file");
  });

  it("keeps preamble text and falls back to unknown file path when header is missing", () => {
    const rawDiff = [
      "warning: generated by test fixture",
      "+++ b/src/from-plus-plus.ts",
      "@@ -0,0 +1,1 @@",
      "+export const x = 1;",
    ].join("\n");

    const chunks = splitByFile(rawDiff);

    expect(chunks).toHaveLength(1);
    expect(chunks[0].filePath).toBe("src/from-plus-plus.ts");
    expect(chunks[0].text).toContain("warning: generated by test fixture");
  });
});

describe("splitDiffForSummarization", () => {
  it("uses hunk splitting for oversized file chunks", () => {
    const rawDiff = [
      "diff --git a/src/oversized.ts b/src/oversized.ts",
      "index 1111111..2222222 100644",
      "--- a/src/oversized.ts",
      "+++ b/src/oversized.ts",
      "@@ -1,2 +1,8 @@",
      "-const value = 1;",
      "+const value = 2;",
      "+const alpha = 1;",
      "+const beta = 2;",
      "@@ -20,2 +26,8 @@",
      "-return oldValue;",
      "+return newValue;",
      "+const gamma = 3;",
      "+const delta = 4;",
    ].join("\n");

    const chunks = splitDiffForSummarization(rawDiff, { maxFileChars: 80, maxHunkChars: 140 });

    expect(chunks.length).toBeGreaterThan(1);
    expect(chunks.every((chunk) => chunk.filePath === "src/oversized.ts")).toBe(true);
    expect(chunks.every((chunk) => chunk.source === "hunk")).toBe(true);
  });

  it("does not split binary patches even when they exceed size threshold", () => {
    const rawDiff = [
      "diff --git a/assets/logo.png b/assets/logo.png",
      "index 1111111..2222222 100644",
      "Binary files a/assets/logo.png and b/assets/logo.png differ",
      "GIT binary patch",
      "literal 0",
      "HcmV?d00001",
    ].join("\n");

    const chunks = splitDiffForSummarization(rawDiff, { maxFileChars: 20, maxHunkChars: 20 });

    expect(chunks).toHaveLength(1);
    expect(chunks[0].isBinary).toBe(true);
    expect(chunks[0].source).toBe("file");
  });
});
